---
- name: Set github_repo URL
  ansible.builtin.set_fact:
    github_repo: 'ssh://git@github.com/'
  when: inventory_hostname in groups['local']
- name: Set github_repo URL
  ansible.builtin.set_fact:
    github_repo: 'https://github.com/'
  when: inventory_hostname in groups['ssh']
- name: clone bin
  ansible.builtin.git:
    repo: "{{ github_repo }}pdostal/homeBIN.git"
    dest: "~/bin"
    accept_hostkey: yes
    force: yes
- name: Clone dotfiles
  ansible.builtin.git:
    repo: "{{ github_repo }}pdostal/dotfiles.git"
    dest: "~/dotfiles"
    accept_hostkey: yes
    force: yes
- name: Apply dotfiles
  ansible.builtin.shell: "~/dotfiles/apply.sh ~ ~/dotfiles"
- name: Ensure .profile exists
  ansible.builtin.file: path=~/.profile state=touch mode=700
  when: inventory_hostname in groups['ssh']
- name: Include .bashrc
  ansible.builtin.lineinfile:
    dest: '~/.profile'
    create: yes
    regexp: '~/.bashrc'
    line: 'source ~/.bashrc'
  when: inventory_hostname in groups['ssh']
- name: Ensure ~/.ssh exists
  ansible.builtin.file: path=~/.ssh state=directory mode=700
